name: 'cookie-dash'
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - ipykernel==6.29.*
    - nb_conda_kernels==2.5.*
    - altair-all==5.5.*
    - dash==2.18.*
    - dash-bootstrap-components==1.7.*
    - plotly==6.0.*
    - tabulate==0.9.*  # df.to_markdown()
    - lxml==5.3.*  # pd.read_html()
    - pandas==2.2.*
    - numpy==2.0.*
    - pip
    - pip:
        - dash-vega-components==0.11.*
        - flask_caching==2.3.*
